#!/bin/sh

# Installing SIMPLE API

# ----------------------------------
# Colors
# ----------------------------------
# shellcheck disable=SC2034
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'






printf "\n"
# shellcheck disable=SC2059
printf "${ORANGE}####### Welcome to the SIMPLE API Installation #######\n"
printf "\n${NOCOLOR}"

read -p "Are you ready to start the installation ? (yes/no)?" choice

case "$choice" in
y | Y | yes)
  printf "\n"
  printf "${ORANGE}Closing Docker if any exists...${NOCOLOR}\n"
  docker-compose down
  printf "${ORANGE}Starting Docker...${NOCOLOR}\n"
  docker-compose up -d --build
  printf "${ORANGE}Waiting some time for database to create...${NOCOLOR}\n"
  sleep 11 # set to 20-30 dont forget to mysql db to create files
  printf "${GREEN}DONE${NOCOLOR}\n"
  printf "${ORANGE}Updating composer and downloading all vendors...${NOCOLOR}\n"
  docker exec -it php74 composer update
  sleep 1
  docker exec -it php74 php bin/console cache:clear
  sleep 1
  printf "${ORANGE}Creating main database if doesnt exists...${NOCOLOR}\n"
  docker exec -it php74 php bin/console doctrine:database:create
  sleep 2
  printf "\n"
  printf "${ORANGE}Last step! Making migrations. Please confirm...${NOCOLOR}\n"
  docker exec -it php74 php bin/console doctrine:migrations:migrate
  sleep 1
  printf "${GREEN}SIMPLE API successfully installed\n"
  sleep 1
  printf "Please remove the install file after installation, you wont need it anymore\n"
  sleep 1
  printf "Open your browser and enter your localhost address ex.: 127.0.0.1 or localhost\n"
  printf "API - localhost/api | localhost/api/docs.json\n"
  sleep 1
  printf "ENJOY ! © Tomas Jucius (jucius.tomas@gmail.com) 2020${NOCOLOR}\n"
  ;;
n | N | no)
  exit
  return 1
  printf "${RED}Installtion was canceled.${NOCOLOR}\n"
  ;;
*)
  exit
  return 1
  printf "${RED}Invalid answer. YES (yes/y/Y) or NO (no/n/N) only${NOCOLOR}\n"
  ;;
esac
